Configurable holidays
meanbee/magento-estimateddelivery pull request #1
Opened 2017-04-27 08:00 UTC by bluec

Added four configurable holiday lists for greater flexibility. This allows the user to define their own holidays instead of only using those available from the gov.uk json feed.

2017-04-27 09:14 UTC, bobbyshaw requested changes
Thanks @bluec, this looks useful!

2017-04-27 09:14 UTC, bobbyshaw commented on .gitignore
> +/.idea
We recommend putting IDE files in your global git ignore (https://help.github.com/articles/ignoring-files/)

2017-04-27 09:17 UTC, bluec commented on .gitignore
> +/.idea
Thanks Tom I've no idea why I don't do that. I already put .DS_Store and others in there; the thought just never occured to me!

2017-04-27 09:21 UTC, bluec commented on .gitignore
> +/.idea
Just let me figure out how on earth to accept this change request. Do I just create a new PR? The github UI is like a labyrinth!

2017-04-27 09:24 UTC, bluec reviewed
@bobbyshaw Have removed .gitignore thanks for the feedback

2017-04-27 09:29 UTC, bobbyshaw approved these changes

2017-04-27 09:29 UTC, merged

2017-04-27 09:30 UTC, bobbyshaw commented
Thanks for the update @bluec. I've merged, I've changed base to the develop branch to try and keep to gitflow methodology.

2017-09-10 15:01 UTC, bluec commented
Hi, could this be merged into master and released? Seems develop and master have got a bit out of sync?

2017-09-11 08:14 UTC, punkstar commented
@bluec Sorted.